### ISSUE TITLE
[GNB] WickedTalon combo not work

### ISSUE THREAD

**Issue by gamer4eg** [Nik-Potokar/XIVComboWayTooAkiiified#10]
oGKD capacities are not used.
(More precisely, they are used incorrectly, only the last oGCD ability in a combo is used)
This works correctly in the base combo plugin. Just take the code from there =)

And another humble question, do you have any plans to combine two GNB combos into one? (Yes, I'm lazy =)

**Comment by Nik-Potokar** [comment]
Fix will be coming in few hours (after my work)

Oh and yes please if you got a suggestion for a combo do let me know what/how it should work and I will add and try to test as much as I can 

(reminder: most of my classes are at 80 so if s feature Is 80+ might need a few updates)

**Comment by Nik-Potokar** [comment]
Meanwhile you can enable the original xivcombo and disable my oGCD feature and enable theirs (both xiv's can be installed at the same time )

**Comment by gamer4eg** [comment]
https://github.com/tssailzz8/XIVComboPluginExpandedest/blob/45cdb3177de6bb7b53d4c68e4fdadc0f6a215e1e/XIVComboPlugin/IconReplacer.cs#L900

Look.
This is the most one-button GNB variant I've seen.
But this is an old version of the combo plugin (before EW).
Just take the code from here.

**Comment by Nik-Potokar** [comment]
Fixed now
