### ISSUE TITLE
[PLD] Circle of Scorn+Spirits/Expiacion

### ISSUE THREAD

**Issue by Trilkin** [Nik-Potokar/XIVComboWayTooAkiiified#12]
There's a feature in Daemitus' fork that puts these on one button and just uses whichever isn't on CD. Would recommend incorporating them into this addon too.

**Comment by Nik-Potokar** [comment]
Should be fixed and added now 
ver 1.5.7

**Comment by Trilkin** [comment]
It's still a little buggy. It shows Spirits Within even with Expiacion unlocked

**Comment by Nik-Potokar** [comment]
Ahh yes i forgot to add level check will be fixed in a few

Thanks

**Comment by Trilkin** [comment]
Fixed as of 1.5.15.
