### ISSUE TITLE
[Suggestion] SMN Mountain Buster Feature

### ISSUE THREAD

**Issue by damolitionn** [Nik-Potokar/XIVComboWayTooAkiiified#17]
When Titan's Favor is up (during the Titan summon), can Gemshine turn into Mountain Buster seeing as it's a GCD into an oGCD cast?

I see the benefit of having it on Ruin III for the Titan Unique Feature but this would streamline the cast even more I feel.

**Comment by Iaotle** [comment]
The whole point is that you don't need to slot gemshine anymore.

**Comment by damolitionn** [comment]
Oh fair enough, my apologies then.
