### ISSUE TITLE
Appreciation and RDM suggestion. 

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/XIVComboWayTooAkiiified#18]
Hi, 

First of all, I wish to express my greatest appreciation to your work here. Greatly improved my enjoyment of the game. Thank you. 

I am posting a suggestion as I cannot find a place to post in your suggested link. My fault here because this is not an issue. 

I was wondering if you can add rdm's new skill (Resolution) to redoublement combo plus.

Thanks again for the wonderful job you are doing.

**Comment by sauronshotdogs** [comment]
They need to be posted in the issues here: https://github.com/Nik-Potokar/MyDalamudPlugins

**Comment by hokeenthong** [comment]
Ah ok. Sorry. I will post the same message there.
