### ISSUE TITLE
Warrior Upheaval 

### ISSUE THREAD

**Issue by opengrip** [Nik-Potokar/XIVComboWayTooAkiiified#24]
Warrior is using upheaval in opener before inner release or storms eye. It is set to only use it during IR or while inner release is on CD but it uses it on cd so it gets popped instantly in opener before you can apply storms eye.

**Comment by Nik-Potokar** [comment]
Will fix later today so it's only using it during storm's eye buff so that it doesn't get used too early.

**Comment by opengrip** [comment]
Awesome thank you!

**Comment by Codemned** [comment]
Which one and why?

**Comment by sauronshotdogs** [comment]
whichever one puts it in front of everything, whenever it is off cd, no matter IR, berserk or whatever

**Comment by Codemned** [comment]
It'll do that if you're level is 70+ and Surging tide buff is present so no additional feature will be needed.

**Comment by sauronshotdogs** [comment]
I like how it is now, because it allows for quick burst of normal mobs.

**Comment by Codemned** [comment]
![itsfine](https://user-images.githubusercontent.com/95727084/146220545-a5982f3c-fc9b-45b5-af85-ffe0610a2076.gif)
If you can't wait the 5? seconds for Surging tide to buff your damage by 10% before needing Upheaval I suggest you clone this repository and change it to your own liking

**Comment by sauronshotdogs** [comment]
I just asked, A simple no would have sufficed.

**Comment by Codemned** [comment]
It's not the question, it's the lack of understanding. You asked for a change to something you haven't seen, haven't tested and didn't understand. The only time as you can probably deduct from the gif, is the first 5 seconds after combat starts where it won't use Upheaval whenever it's available.

**Comment by Codemned** [comment]
You're request has been reviewed and declined.

**Comment by opengrip** [comment]
A small burst within the first 2 gcds isn't going to be useful 99.9% of the time vs saving your upheaval for the damage boost from Surging Tempest. Even most trash at equal level don't die that quickly. And while I'm typing I figured it would be a good idea to confirm that Orogeny also waits for the ST buff if it doesn't already. :)

**Comment by Codemned** [comment]
This has been implemented.
