### ISSUE TITLE
PLD Confiteor Low Level

### ISSUE THREAD

**Issue by opengrip** [Nik-Potokar/XIVComboWayTooAkiiified#26]
Before Pld gets Confiteor using requiescat results in your skill turning to Confiteor without a way to use the last stack from requiescat since you don't actually gain Confiteor till level 80.  This effects leveling or lower level dungeons between 68-80. Workaround for now is keeping a separate bind of holy spirit but having a conditional set to only change your holy spirit to Confiteor after level 80 would be nice :)

**Comment by Codemned** [comment]
Missing level check added to Requiescat Feature.
Thanks for letting us know.
