### ISSUE TITLE
Ninja Huton/Armor Crush Combo at <40s  | How to change?

### ISSUE THREAD

**Issue by El0quenz** [Nik-Potokar/XIVComboWayTooAkiiified#3]
Hello,

I love the Ninja Huton/Armor crush combo feature. It works very well!

I've looked through your Combo files and found this on line #78

`                    if (lastComboMove == NIN.GustSlash && level >= 45 && huton.HutonTimer < 30000)
`

Would it be possible to raise that timer to <4000 aka. do Armor Crush if Huton is less than 40s?

The problem, I don't know how to compile the changed file, so I could try it out for myself.
This is why I am asking you for your help. 

How can I make this work in the actual Plugin, or how do I compile it after I changed the File myself?

Would be awesome if you could help me out with that.

Regards

**Comment by El0quenz** [comment]
With the help of the Dalamud Discord and some nice people I figured out how to compile your Source Code on my own! 
I have it now working for <40s!

Thank you so much for your great work!
If you don't mind I could make a Fork with that change for other people, but I am new into GitHub, so I am not sure of the right etiquette.

Regardless, thank you.

**Comment by Nik-Potokar** [comment]
Hey I'm sorry for a late reply

You can make all the changes you want ^^

I will be adding some new stuff shortly aswell
