### ISSUE TITLE
PLD Royal Authority combo broken at <60 content

### ISSUE THREAD

**Issue by Hallrider** [Nik-Potokar/XIVComboWayTooAkiiified#30]
PLD Royal Authority combo breaks before lvl60. The combo should replace Royal Authority with its lower level version (Rage of Halone) in sub-60 content, but instead swaps to Royal Authority on the bar. In dungeons it's possible to hit Rage of Halone if timed correctly, however if you miss the CD for it, it will not function.

**Comment by Codemned** [comment]
Fixed.

**Comment by Hallrider** [comment]
Thanks for the update, however it doesn't seem to work still. The Royal Authority Combo now goes Fast Blade -> Riot Blade -> Rinse and repeat, it will keep repeating 1-2 and never get to Rage of Halone if you don't have Royal Authority unlocked (at lvl60).

**Comment by Codemned** [comment]
You should have reopened this. Then I would've fixed it properly sooner.
