### ISSUE TITLE
its not Really Issue, im a new developer myself and im inspired by yr project to work more for ff14

### ISSUE THREAD

**Issue by xZyph3r** [Nik-Potokar/XIVComboWayTooAkiiified#33]
my question is how u get the uint from every spell in the combo  folder

**Comment by Nik-Potokar** [comment]
I personally use galland tools database website but another option is also xivapi to get all the IDs

[Galland](https://www.garlandtools.org/db/)

**Comment by xZyph3r** [comment]
hey thx for yr answer where do i have to look on garland, im for example on the ability Bootshine but i dont find the uint from it

**Comment by xZyph3r** [comment]
nvm i found it thx u

**Comment by Nik-Potokar** [comment]
Oh great was just about to guide you ^^
