### ISSUE TITLE
[NINJA] Please remove the transition of Armor Crush in Aeolian Edge combo when Huton buff below 30 sec

### ISSUE THREAD

**Issue by ksledu** [Nik-Potokar/XIVComboWayTooAkiiified#45]
![image](https://user-images.githubusercontent.com/96337656/146671337-65dfd4f0-f663-455b-aff0-d986f7f9d275.png)

Hi Nik. picture above is my ninja setting. the current main combo logic is that Aeolian edge will be replaced with armor crush automatically when huton buff less than 30 sec,which in order to extend buff to 60 sec.  I acknowledge that setting can make combo more convenient, but meanwhile it comes with two disadvantage:

1) Armor Crush is lv54 skill. it would becomes 'invalid' when the player in dungeon which below lv54 (for example: Main Scenario Quests ). it make main combo stuck while huton buff less than 30 sec.

2) Armor Crush and Aeolian Edge both are positional skills.  it will cause potency loss when the plugin change aeolian edge to armor crush suddenly and player does not aware of the change .

Is it possible to take the armor crush out of Aeolian edge combo or make it as an individual feature (people can enable or disable by themselves) .  Thanks in advance.

**Comment by Iaotle** [comment]
Don't even see it committed to git. Might need another pass.

**Comment by Nik-Potokar** [comment]
Fixed and updated
