### ISSUE TITLE
SMN Easy rotation feature not changing icons for bahamut

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVComboWayTooAkiiified#5]
Also doesn't do enkindle bahamut. Phoenix works like a dream though.

**Comment by Nik-Potokar** [comment]
Hey there!

So i've managed to fix the issue ( incorrect version pushed) [Link to 1.0.0.5 Fix](https://github.com/Nik-Potokar/XIVComboWayTooAkiiified/releases/tag/tag)

Please let me know if any of the issues persist or if the timings on bahamut phase need adjusting.
