### ISSUE TITLE
Warrior issue

### ISSUE THREAD

**Issue by Cerezachesire** [Nik-Potokar/XIVComboWayTooAkiiified#8]
Hi,
Currently testing your fork in game on warrior and noticed that storm's path combo chain does not change to storm's path but to storms eye, just a heads up :)

ty for the amazing fork tho!

**Comment by Nik-Potokar** [comment]
Hey thanks for the heads up ^^

Yeah i've noticed that today i will try to get around to fixing it asap (today/tomorrow) latest <3

**Comment by Cerezachesire** [comment]
will def do, thanks a lot <3! keep up the great work

**Comment by Nik-Potokar** [comment]
Warrior fix should be live in a few min

If there is any other issues you come across please let me know <3
